static class PaletteTypes{
  
  static int[][][] paletteTable = {
    {DefinedColors.user1, DefinedColors.user2},
    {DefinedColors.pink, DefinedColors.transparent},
    {DefinedColors.pink, DefinedColors.yellow},
    {DefinedColors.pink, DefinedColors.green},
    {DefinedColors.pink, DefinedColors.orange},
    {DefinedColors.pink, DefinedColors.violet},
    {DefinedColors.pink, DefinedColors.rubyRed},
    {DefinedColors.pink, DefinedColors.deepTurquoise},
    {DefinedColors.pink, DefinedColors.white},
    {DefinedColors.pink, DefinedColors.black},

    {DefinedColors.pink, DefinedColors.user1},
    {DefinedColors.pink, DefinedColors.user2},
    {DefinedColors.yellow, DefinedColors.transparent},
    {DefinedColors.yellow, DefinedColors.green},
    {DefinedColors.yellow, DefinedColors.orange},
    {DefinedColors.yellow, DefinedColors.violet},
    {DefinedColors.yellow, DefinedColors.rubyRed},
    {DefinedColors.yellow, DefinedColors.deepTurquoise},
    {DefinedColors.yellow, DefinedColors.white},
    {DefinedColors.yellow, DefinedColors.black},

    {DefinedColors.yellow, DefinedColors.user1},
    {DefinedColors.yellow, DefinedColors.user2},
    {DefinedColors.green, DefinedColors.transparent},
    {DefinedColors.green, DefinedColors.orange},
    {DefinedColors.green, DefinedColors.violet},
    {DefinedColors.green, DefinedColors.rubyRed},
    {DefinedColors.green, DefinedColors.deepTurquoise},
    {DefinedColors.green, DefinedColors.white},
    {DefinedColors.green, DefinedColors.black},
    {DefinedColors.green, DefinedColors.user1},

    {DefinedColors.green, DefinedColors.user2},
    {DefinedColors.orange, DefinedColors.transparent},
    {DefinedColors.orange, DefinedColors.violet},
    {DefinedColors.orange, DefinedColors.rubyRed},
    {DefinedColors.orange, DefinedColors.deepTurquoise},
    {DefinedColors.orange, DefinedColors.white},
    {DefinedColors.orange, DefinedColors.black},
    {DefinedColors.orange, DefinedColors.user1},
    {DefinedColors.orange, DefinedColors.user2},
    {DefinedColors.violet, DefinedColors.transparent},

    {DefinedColors.violet, DefinedColors.rubyRed},
    {DefinedColors.violet, DefinedColors.deepTurquoise},
    {DefinedColors.violet, DefinedColors.white},
    {DefinedColors.violet, DefinedColors.black},
    {DefinedColors.violet, DefinedColors.user1},
    {DefinedColors.violet, DefinedColors.user2},
    {DefinedColors.rubyRed, DefinedColors.transparent},
    {DefinedColors.rubyRed, DefinedColors.deepTurquoise},
    {DefinedColors.rubyRed, DefinedColors.white},
    {DefinedColors.rubyRed, DefinedColors.black},

    {DefinedColors.rubyRed, DefinedColors.user1},
    {DefinedColors.rubyRed, DefinedColors.user2},
    {DefinedColors.deepTurquoise, DefinedColors.transparent},
    {DefinedColors.deepTurquoise, DefinedColors.white},
    {DefinedColors.deepTurquoise, DefinedColors.black},
    {DefinedColors.deepTurquoise, DefinedColors.user1},
    {DefinedColors.deepTurquoise, DefinedColors.user2},
    {DefinedColors.white, DefinedColors.transparent},
    {DefinedColors.white, DefinedColors.black},
    {DefinedColors.white, DefinedColors.user1},

    {DefinedColors.white, DefinedColors.user2},
    {DefinedColors.black, DefinedColors.transparent},
    {DefinedColors.black, DefinedColors.user1},
    {DefinedColors.black, DefinedColors.user2},
    {DefinedColors.transparent, DefinedColors.user1},
    {DefinedColors.transparent, DefinedColors.user2}
  };
}

